// Copyright (c) 2017, 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: cdi-intro
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2018-03-09
:page-guide-category: microprofile
:page-essential: true
:page-essential-order: 2
:page-description: Learn how to use Contexts and Dependency Injection (CDI) to manage and inject dependencies into microservices.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Jakarta EE']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Managing and injecting dependencies into Java microservices using Contexts and Dependency Injection (CDI)
:page-seo-description: A getting started tutorial with examples of how to manage scopes and inject dependencies into Java microservices using Contexts and Dependency Injection (CDI).
:figure-caption!:
= Injecting dependencies into microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use Contexts and Dependency Injection (CDI) to manage scopes and inject dependencies into microservices.

== What you'll learn

You will learn how to use Contexts and Dependency Injection (CDI) to manage scopes and inject dependencies in a simple inventory management application.

The application that you will be working with is an `inventory` service, which stores the information about various JVMs that run on different systems. Whenever a request is made to the `inventory` service to retrieve the JVM system properties of a particular host, the `inventory` service communicates with the `system` service on that host to get these system properties. The system properties are then stored and returned.

You will use scopes to bind objects in this application to their well-defined contexts. CDI provides a variety of scopes for you to work with and while you will not use all of them in this guide, there is one for almost every scenario that you may encounter. Scopes are defined by using CDI annotations. You will also use dependency injection to inject one bean into another to make use of its functionalities. This enables you to inject the bean in its specified context without having to instantiate it yourself.

The implementation of the application and its services are provided for you in the `start/src` directory. The `system` service can be found in the `start/src/main/java/io/openliberty/guides/system` directory, and the `inventory` service can be found in the `start/src/main/java/io/openliberty/guides/inventory` directory. If you want to learn more about RESTful web services and how to build them, see https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^] for details about how to build the `system` service. The `inventory` service is built in a similar way.

=== What is CDI?

Contexts and Dependency Injection (CDI) defines a rich set of complementary services that improve the application structure. The most fundamental services that are provided by CDI are contexts that bind the lifecycle of stateful components to well-defined contexts, and dependency injection that is the ability to inject components into an application in a typesafe way. With CDI, the container does all the daunting work of instantiating dependencies, and controlling exactly when and how these components are instantiated and destroyed.


// =================================================================================================
// Getting started
// =================================================================================================

[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro.adoc[]

Point your browser to the http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] URL.
This is the starting point of the `inventory` service and it displays the current contents of the inventory. As you might expect, these are empty because nothing is stored in the inventory yet. Next, point your browser to the http://localhost:9080/inventory/systems/localhost[http://localhost:9080/inventory/systems/localhost^] URL.
You see a result in JSON format with the system properties of your local JVM. When you visit this URL, these system properties are automatically stored in the inventory. Go back to http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^]
and you see a new entry for `localhost`. For simplicity, only the OS name and username are shown here for each host. You can repeat this process for your own hostname or any other machine that is running the `system` service.

[role='command']
include::{common-includes}/twyb-end.adoc[]

== Handling dependencies in the application

You will use CDI to inject dependencies into the inventory manager application and learn how to manage the life cycles of your objects.

=== Managing scopes and contexts

Navigate to the `start` directory to begin.
ifdef::cloud-hosted[]
```bash
cd /home/project/guide-cdi-intro/start
```
endif::[]

[role='command']
include::{common-includes}/devmode-lmp33-start.adoc[]

[role="code_command hotspot", subs="quotes"]
----
#Create the `InventoryManager` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java`
----
InventoryManager.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[]
----

This bean contains two simple functions. The [hotspot=add file=0]`add()` function is for adding entries to the inventory. The [hotspot=list file=0]`list()` function is for listing all the entries currently stored in the inventory.

This bean must be persistent between all of the clients, which means multiple clients need to share the same instance. To achieve this by using CDI, you can simply add the [hotspot=ApplicationScoped file=0]`@ApplicationScoped` annotation onto the class.

This annotation indicates that this particular bean is to be initialized once per application. By making it application-scoped, the container ensures that the same instance of the bean is used whenever it is injected into the application.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `InventoryResource` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----
InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

The inventory resource is a RESTful service that is served at the `inventory/systems` endpoint. 

Annotating a class with the [hotspot=ApplicationScoped file=1]`@ApplicationScoped` annotation indicates that the bean is initialized once and is shared between all requests while the application runs.

If you want this bean to be initialized once for every request, you can annotate the class with the `@RequestScoped` annotation instead. With the `@RequestScoped` annotation, the bean is instantiated when the request is received and destroyed when a response is sent back to the client. A request scope is short-lived.

=== Injecting a dependency

Refer to the [hotspot=InventoryResource file=0]`InventoryResource` class you created above.

The [hotspot=inject hotspot=inject2 file=0]`@Inject` annotation indicates a dependency injection. You are injecting your `InventoryManager` and `SystemClient` beans into the `InventoryResource` class. This injects the beans in their specified context and makes all of their functionalities available without the need of instantiating them yourself. The injected bean `InventoryManager` can then be invoked directly through the [hotspot=managerAdd file=0]`manager.add(hostname, props)` and [hotspot=managerList file=0]`manager.list()` function calls. The injected bean `SystemClient` can be invoked through the [hotspot=properties file=0]`systemClient.getProperties(hostname)` function call.

Finally, you have a client component [hotspot file=1]`SystemClient` that can be found in the `src/main/java/io/openliberty/guides/inventory/client` directory. This class communicates with the `system` service to retrieve the JVM system properties for a particular host that exposes them. This class also contains detailed Javadocs that you can read for reference.

Your inventory application is now completed.

InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

SystemClient.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[]
----

// =================================================================================================
// Running the application
// =================================================================================================

[role='command']
include::{common-includes}/devmode-build.adoc[]

You can find the `inventory` and `system` services at the following URLs:

* http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^]
* http://localhost:9080/system/properties[http://localhost:9080/system/properties^]

// =================================================================================================
// Testing
// =================================================================================================

== Testing the inventory application

While you can test your application manually, you should rely on automated tests because they trigger a failure whenever a code change introduces a defect. Because the application is a RESTful web service application, you can use JUnit and the RESTful web service Client API to write tests. In testing the functionality of the application, the scopes and dependencies are being tested.

[role="code_command hotspot", subs="quotes"]
----
#Create the `InventoryEndpointIT` class.#
`src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java`
----

InventoryEndpointIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java[]
----

The [hotspot=BeforeAll file=0]`@BeforeAll` annotation is placed on a method that runs before any of the test cases. In this case, the [hotspot=oneTimeSetup file=0]`oneTimeSetup()` method retrieves the port number for the Open Liberty and builds a base URL string that is used throughout the tests.

The [hotspot=BeforeEach file=0]`@BeforeEach` and [hotspot=AfterEach file=0]`@AfterEach` annotations are placed on methods that run before and after every test case. These methods are generally used to perform any setup and teardown tasks. In this case, the [hotspot=setup file=0]`setup()` method creates a JAX-RS client, which makes HTTP requests to the `inventory` service. The [hotspot=teardown file=0]`teardown()` method simply destroys this client instance.

See the following descriptions of the test cases:

* [hotspot=testHostRegistration file=0]`testHostRegistration()` verifies that a host is correctly added to the inventory.

* [hotspot=testSystemPropertiesMatch file=0]`testSystemPropertiesMatch()` verifies that the JVM system properties returned by the `system` service match the ones stored in the `inventory` service.

* [hotspot=testUnknownHost file=0]`testUnknownHost()` verifies that an unknown host or a host that does not expose their JVM system properties is correctly handled as an error.

To force these test cases to run in a particular order, annotate your [hotspot file=0]`InventoryEndpointIT` test class with the [hotspot=TestMethodOrder file=0]`@TestMethodOrder(OrderAnnotation.class)` annotation. [hotspot=TestMethodOrder file=0]`OrderAnnotation.class` runs test methods in numerical order, according to the values specified in the [hotspot=Order1 hotspot=Order2 hotspot=Order3 file=0]`@Order` annotation. You can also create a custom `MethodOrderer` class or use built-in `MethodOrderer` implementations, such as `OrderAnnotation.class`, `Alphanumeric.class`, or `Random.class`. Label your test cases with the [hotspot=Test1 hotspot=Test2 hotspot=Test3 file=0]`@Test` annotation so that they automatically run when your test class runs.

Finally, the [hotspot file=1]`src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java` file is included for you to test the basic functionality of the `system` service. If a test failure occurs, then you might have introduced a bug into the code.

SystemEndpointIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java[]
----

// =================================================================================================
// Running the tests
// =================================================================================================

[role='command']
include::{common-includes}/devmode-test.adoc[]

If the tests pass, you see a similar output to the following example:

[source, role='no_copy']
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.99 sec - in it.io.openliberty.guides.system.SystemEndpointIT
Running it.io.openliberty.guides.inventory.InventoryEndpointIT
[err] Runtime exception: RESTEASY004655: Unable to invoke request: java.net.UnknownHostException: badhostname: nodename nor servname provided, or not known
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.325 sec - in it.io.openliberty.guides.inventory.InventoryEndpointIT

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

The error messages are expected and result from a request to a bad or an unknown hostname. This request is made in the `testUnknownHost()` test from the `InventoryEndpointIT` integration test.

To see whether the tests detect a failure, change the [hotspot=endpoint file=0]`endpoint` for the `inventory` service in the [hotspot file=0]`src/main/java/io/openliberty/guides/inventory/InventoryResource.java` file to something else. Then, run the tests again to see that a test failure occurs.

InventoryResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
----

[role='command']
include::{common-includes}/devmode-quit.adoc[]

== Great work! You're done!

You just used CDI services in Open Liberty to build a simple inventory application.

include::{common-includes}/attribution.adoc[subs="attributes"]
