// Copyright (c) 2017, 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: cdi-intro
:page-layout: guide
:page-duration: 15 minutes
:page-releasedate: 2017-12-11
:page-description: Learn how to use CDI in a RESTful web service.
:page-tags: ['CDI', 'REST']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:figure-caption!:
= Handling dependencies with RESTful web services

Learn how to use Contexts and Dependency Injection to manage and inject dependencies into RESTful web services.

== What you'll learn

You will learn how to use CDI in a simple inventory management application to manage scopes and inject dependencies.

The application that you will be working with is an `inventory` service
which stores the information about various JVMs running on different systems.
Whenever a request is made to the `inventory` service to retrieve the JVM
system properties of a particular host, the `inventory` service will communicate with the `system`
service on that host to get these system properties. The system properties are then stored and returned.

You will use scopes to bound objects in this application to their well defined-contexts.
CDI provides a variety of scopes for you to work with and while you will not use all of them in this guide,
there is one for almost every scenario that you may encounter. Scopes are defined using CDI annotations.
You will also use dependency injection to inject one bean into another to make use of its functionalities.
This enables you to inject the bean in its specified context without having to instantiate it yourself.

The implementation of the application and its services are provided for you under the `start/src` directory.
The `system` service can be found
under `start/src/main/java/io/openliberty/guides/system`, and the `inventory` service can be found
under `start/src/main/java/io/openliberty/guides/inventory`.
If you want to learn more about RESTful web services and how to build them, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service]
which has details on how to build the `system` service.
The `inventory` service is built in a similar way.

=== What is CDI?

Contexts and Dependency Injection (CDI) defines a rich set of complementary services that improve the application structure.
The most fundamental services provided by CDI are Contexts that bind the lifecycle of stateful components to well-defined contexts,
and Dependency Injection that is the ability to inject components into an application in a typesafe way.
With CDI, the container does all the daunting work of instantiating dependencies, and
controlling exactly when and how these components are instantiated and destroyed.


== Getting started

The fastest way to work through this guide is to clone the git repository and use the starting project
that is provided in the `start` directory. To do this, run the following commands:

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-cdi-intro.git
cd guide-cdi-intro/start
----

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished inventory application. Feel
free to give it a try before you proceed.

To try out the application, first navigate to the `finish` directory and then run the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```

Point your browser to http://localhost:9080/inventory/systems. This is the staring point of the `inventory`
service and it displays the current contents of the inventory. As you might expect, these are empty since
nothing is stored in the inventory yet. Next, point your browser to http://localhost:9080/inventory/systems/localhost.
You see a result in JSON format with the system properties of your local JVM. By visiting this URL, these system
properties are automatically stored in the inventory. Go back to http://localhost:9080/inventory/systems and
you see a new entry for `localhost`. For simplicity, only the OS name and username are shown here for
each host. You can repeat this process for your own hostname or any other machine that is running
the `system` service.

Once you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.


== Handling dependencies in the application

You will use CDI to inject dependencies into the inventory manager application and
you will learn how to manage the life cycles of your objects.

=== Managing scopes and contexts

Take a look at `src/main/java/io/openliberty/guides/inventory/InventoryManager.java`.

This bean contains two simple functions. One function is for retrieving (get) entries from calling the `system` service,
and then add it to the inventory list.
The second function is for listing (list) all the entries currently stored in the inventory.
This bean must be persistent between all the clients.

To do that, add the `@ApplicationScoped` annotation on the class.
This annotation indicates that this particular
bean is to be initialized once per application.
By making it application-scoped, the container ensures that the same instance of the bean is used whenever
it is injected into the application.

Your completed class looks like this:

[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=**;!copyright;]
----

Next, refer to `src/main/java/io/openliberty/guides/inventory/InventoryResource.java`.
The inventory resource is a RESTful service that is served at the `inventory/systems` endpoint. It enables the client to
communicate with the inventory manager via HTTP methods.

Add the `@RequestScoped` annotation on the class to indicate that this bean is
to be initialized once for every request. In other words, the bean is instantiated when the request
is received and destroyed when a response is sent back to the client. Note that while this bean can
also be application-scoped, request scope is short-lived and is therefore ideal for HTTP requests.

=== Injecting a dependency

Add `@Inject InventoryManager manager;` annotation on the class
`src/main/java/io/openliberty/guides/inventory/InventoryResource.java`.

Your completed class looks like this:

[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=**;!copyright]
----

This annotation indicates a dependency injection.
You are injecting your `InventoryManager` bean into the `InventoryResource` class.
This injects the bean in its specified context (application-scoped) and makes all of its functionalities
available without the need of instantiating it yourself.
The injected bean can then be invoked directly via the `manager.get(hostname)`
and `manager.list()` function calls.

Finally, we're giving you an client component `SystemClient`.
It can be found under `src/main/java/io/openliberty/guides/inventory/client`.
This class is responsible for communicating with the `system` service to
retrieve the JVM system properties for a particular host that exposes them.

This class also contains detailed Javadocs, so feel free to read them for reference.

Your inventory application is now completed.

// =================================================================================================
// Building the application
// =================================================================================================

== Building and running the application

// include::{common-includes}/mvnbuild.adoc[]

To build the application, run the Maven `install` goal from the command line:

```
mvn install
```

This goal builds the application and creates a `.war` file in the target directory. The goal also
configures and installs Open Liberty into the `target/liberty/wlp` directory.

Next, run the Maven `liberty:start-server` goal:

```
mvn liberty:start-server
```

This goal starts an Open Liberty server instance. Your Maven `pom.xml` is already configured to start
the application in this server instance.

You can find the `inventory` and `system` services at:

- http://localhost:9080/inventory/systems
- http://localhost:9080/system/properties

// include::{common-includes}/mvnpackage.adoc[]

If you make changes to the code, use the Maven `package` goal to rebuild the application and have the
running Open Liberty server pick them up automatically:

```
mvn package
```

To stop the Open Liberty server, run the Maven `liberty:stop-server` goal:

```
mvn liberty:stop-server
```


// =================================================================================================
// Testing
// =================================================================================================

== Testing the inventory application

While you can test your application manually, you should rely on automated tests since they will trigger
a failure whenever a code change introduces a defect.
Since the application is a RESTful web service application, you can use
JUnit and the RESTful web service Client API to write tests.
In testing the functionality of the application, the scopes and dependencies are being tested.

Create test class `src/test/java/it/io/openliberty/guides/inventory/EndpointTest.java`:

[source, Java]
----
include::finish/src/test/java/it/io/openliberty/guides/inventory/EndpointTest.java[tags=**;!copyright;!javadoc]
----

The `@BeforeClass` annotation is placed on a method that executes before any of the test cases.
In this case, the `oneTimeSetup` method retrieves the port number for the Open Liberty server and builds
a base URL string that is used throughout the tests.

The `@Before` and `@After` annotations are placed on methods that execute before and after every test case.
These methods are generally used to perform any setup and teardown tasks. In this case, the `setup` method
creates a JAX-RS client which makes HTTP requests to the `inventory` service. This client must
also be registered with a JSON-P provider (`JsrJsonpProvider`) to process JSON resources. The `teardown`
method simply destroys this client instance.

Let's break down the test cases:

- `testEmptyInventory()` verifies that the inventory is initially empty when the server first starts up.
- `testHostRegistration()` verifies that a host is correctly added to the inventory.
- `testSystemPropertiesMatch()` verifies that the JVM system properties returned by the `system` service match
the ones stored in the `inventory` service.
- `testUnknownHost()` verifies that an unknown host or a host that does not expose their JVM system
properties is correctly handled as an error.

To force these test cases to execute in a particular order, put them in a `testSuite()` method and label
it with a `@Test` annotation so that it automatically executes when your test class run.

Finally, notice that you're using a few helper methods throughout the tests.
You can find complete Javadocs for these under the `finish` directory for reference:
`finish/src/test/java/it/io/openliberty/guides/inventory/EndpointTest.java`.


=== Running the tests

// include::{common-includes}/mvnverify.adoc[]

If the server is still running from the previous steps, stop it first using the Maven `liberty:stop-server` goal:

```
mvn liberty:stop-server
```

Then, verify that the tests pass using the Maven `verify` goal:

```
mvn verify
```

It may take some time before build is complete. If the tests pass, you will see an output similar to the following:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.128 sec - in it.io.openliberty.guides.inventory.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, change the endpoint for the `inventory` service in
`src/main/java/io/openliberty/guides/inventory/InventoryResource.java` to something else, then
re-run the Maven build. You will see a test failure occur.


== Great work! You're done!

You have just completed building a simple inventory application on top of Open Liberty using CDI services.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and
expand on top what you built in this guide.

include::{common-includes}/finish.adoc[]
